# CI script for building Wine

.wine-build:
  stage: build
  image: $CI_REGISTRY/wine/wine:debian-bullseye
  interruptible: true
  cache:
    - paths:
        - ccache/
    - key:
        files:
          - configure.ac
      paths:
        - build32/config.cache
        - build64/config.cache
  before_script:
    - export BASEDIR="$PWD"
    - export CCACHE_BASEDIR="$BASEDIR"
    - export CCACHE_DIR="$BASEDIR/ccache"
    - export CCACHE_COMPILERCHECK=content
    - export PATH="/usr/lib/ccache:$PATH"
    - mkdir -p build32 build64

build-linux:
  extends: .wine-build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    when: on_failure
    paths:
      - build64/config.log
      - build32/config.log
  script:
    - rm -fr .git/rebase-merge  # in case a previous CI run failed in git rebase
    - git rebase $CI_MERGE_REQUEST_DIFF_BASE_SHA --exec ./tools/gitlab/build-linux

build-mac:
  extends: .wine-build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  tags:
    - mac
  artifacts:
    when: on_failure
    paths:
      - build64/config.log
      - build32/config.log
  script:
    - rm -fr .git/rebase-merge
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - git rebase $CI_MERGE_REQUEST_DIFF_BASE_SHA --exec ./tools/gitlab/build-mac

build-winetest:
  extends: .wine-build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'trigger' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    name: winetest
    paths:
      - winetest.exe
      - winetest64.exe
  script:
    - cd build64
    - ../configure -q -C --enable-win64 --with-mingw
    - make -s -j$(nproc) install-test DESTDIR=$BASEDIR
    - cd ../build32
    - ../configure -q -C --with-mingw
    - make -s -j$(nproc) install-test DESTDIR=$BASEDIR
    - cd ..
    - mv usr/local/lib/wine/i386-windows/winetest.exe winetest.exe
    - mv usr/local/lib/wine/x86_64-windows/winetest.exe winetest64.exe
